### ISSUE TITLE
Error: Reason: DestinationProperty: Property must be set. but is set in Visual Studio

### ISSUE THREAD

**Issue by mwiorek** [BizTalkComponents/PromoteNewGuid#1]
When using Visual Studio 2013 and BizTalk Server 2013R2 there is a problem when adding the DestinationProperty directly in Visual Studio. When deploying the solution from Visual Studio, BizTalk does not seem to recognize that a value is provided to the pipeline component and gives an error `There was a failure executing the send pipeline:...Source: "PromoteNewGuid" Send Port: ...Reason: DestinationProperty: Property must be set`.  even though a property is set and the property is available in the send port and in the pipeline configuration dialog in BizTalk Administration Console.

![image](https://cloud.githubusercontent.com/assets/2902317/18379887/163dd3fa-7675-11e6-8149-df10dd0f9a6d.png)
_In Visual Studio_

![image](https://cloud.githubusercontent.com/assets/2902317/18379984/8ca6a2f6-7675-11e6-9281-4c271c7a1f77.png)
_In BizTalk Administration Console_
## Workaround

If DestinationProperty is left blank i visual studio and added through the BizTalk Administration Console the pipeline works as expected. 

![image](https://cloud.githubusercontent.com/assets/2902317/18380120/290a6768-7676-11e6-868f-688335ec52fc.png)
_In Visual Studio_
![image](https://cloud.githubusercontent.com/assets/2902317/18380145/45bd337c-7676-11e6-8da8-a9ebe2b315e6.png)
_In BizTalk Administration Console_

**Comment by robinhultman** [comment]
I wasn't able to reproduce this but I know that there has been some problems with the old version of the Utils library. Could you try the new release?

**Comment by fernandodsanjos** [comment]
I got the same problem, seams like the propertybag is not read correctly

**Comment by mwiorek** [comment]
The new release works as expected and the issue has been resolved
